/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PoliticasSeguridadRouteImport } from './routes/politicas-seguridad'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as CategoriaIdRouteImport } from './routes/categoria.$id'
import { Route as AuthVerificarTelefonoRouteImport } from './routes/auth.verificar-telefono'
import { Route as AuthRecuperarRouteImport } from './routes/auth.recuperar'
import { Route as AuthNuevaContrasenaRouteImport } from './routes/auth.nueva-contrasena'
import { Route as AuthenticatedSoporteRouteImport } from './routes/_authenticated/soporte'
import { Route as AuthenticatedPublicarRouteImport } from './routes/_authenticated/publicar'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNotificacionesRouteImport } from './routes/_authenticated/notificaciones'
import { Route as AuthenticatedMisPublicacionesRouteImport } from './routes/_authenticated/mis-publicaciones'
import { Route as AuthenticatedMisPagosRouteImport } from './routes/_authenticated/mis-pagos'
import { Route as AuthenticatedMisDestacadosRouteImport } from './routes/_authenticated/mis-destacados'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as VendedorVendedorIdReseChar241asRouteImport } from './routes/vendedor.$vendedorId.reseñas'
import { Route as AuthenticatedReseChar241aTransaccionIdRouteImport } from './routes/_authenticated/reseña.$transaccionId'
import { Route as AuthenticatedPromocionarProductoIdRouteImport } from './routes/_authenticated/promocionar.$productoId'
import { Route as AuthenticatedEditarIdRouteImport } from './routes/_authenticated/editar.$id'
import { Route as AuthenticatedChatChatIdRouteImport } from './routes/_authenticated/chat.$chatId'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasSeguridadRoute = PoliticasSeguridadRouteImport.update({
  id: '/politicas-seguridad',
  path: '/politicas-seguridad',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaIdRoute = CategoriaIdRouteImport.update({
  id: '/categoria/$id',
  path: '/categoria/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerificarTelefonoRoute = AuthVerificarTelefonoRouteImport.update({
  id: '/verificar-telefono',
  path: '/verificar-telefono',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNuevaContrasenaRoute = AuthNuevaContrasenaRouteImport.update({
  id: '/nueva-contrasena',
  path: '/nueva-contrasena',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSoporteRoute = AuthenticatedSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublicarRoute = AuthenticatedPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacionesRoute =
  AuthenticatedNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMisPublicacionesRoute =
  AuthenticatedMisPublicacionesRouteImport.update({
    id: '/mis-publicaciones',
    path: '/mis-publicaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMisPagosRoute = AuthenticatedMisPagosRouteImport.update({
  id: '/mis-pagos',
  path: '/mis-pagos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisDestacadosRoute =
  AuthenticatedMisDestacadosRouteImport.update({
    id: '/mis-destacados',
    path: '/mis-destacados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VendedorVendedorIdReseChar241asRoute =
  VendedorVendedorIdReseChar241asRouteImport.update({
    id: '/vendedor/$vendedorId/reseñas',
    path: '/vendedor/$vendedorId/reseñas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReseChar241aTransaccionIdRoute =
  AuthenticatedReseChar241aTransaccionIdRouteImport.update({
    id: '/reseña/$transaccionId',
    path: '/reseña/$transaccionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromocionarProductoIdRoute =
  AuthenticatedPromocionarProductoIdRouteImport.update({
    id: '/promocionar/$productoId',
    path: '/promocionar/$productoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditarIdRoute = AuthenticatedEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatChatIdRoute = AuthenticatedChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/politicas-seguridad': typeof PoliticasSeguridadRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/mis-destacados': typeof AuthenticatedMisDestacadosRoute
  '/mis-pagos': typeof AuthenticatedMisPagosRoute
  '/mis-publicaciones': typeof AuthenticatedMisPublicacionesRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/publicar': typeof AuthenticatedPublicarRoute
  '/soporte': typeof AuthenticatedSoporteRoute
  '/auth/nueva-contrasena': typeof AuthNuevaContrasenaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/verificar-telefono': typeof AuthVerificarTelefonoRoute
  '/categoria/$id': typeof CategoriaIdRoute
  '/producto/$id': typeof ProductoIdRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
  '/promocionar/$productoId': typeof AuthenticatedPromocionarProductoIdRoute
  '/reseña/$transaccionId': typeof AuthenticatedReseChar241aTransaccionIdRoute
  '/vendedor/$vendedorId/reseñas': typeof VendedorVendedorIdReseChar241asRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/politicas-seguridad': typeof PoliticasSeguridadRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/mis-destacados': typeof AuthenticatedMisDestacadosRoute
  '/mis-pagos': typeof AuthenticatedMisPagosRoute
  '/mis-publicaciones': typeof AuthenticatedMisPublicacionesRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/publicar': typeof AuthenticatedPublicarRoute
  '/soporte': typeof AuthenticatedSoporteRoute
  '/auth/nueva-contrasena': typeof AuthNuevaContrasenaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/verificar-telefono': typeof AuthVerificarTelefonoRoute
  '/categoria/$id': typeof CategoriaIdRoute
  '/producto/$id': typeof ProductoIdRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
  '/promocionar/$productoId': typeof AuthenticatedPromocionarProductoIdRoute
  '/reseña/$transaccionId': typeof AuthenticatedReseChar241aTransaccionIdRoute
  '/vendedor/$vendedorId/reseñas': typeof VendedorVendedorIdReseChar241asRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/politicas-seguridad': typeof PoliticasSeguridadRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/mis-destacados': typeof AuthenticatedMisDestacadosRoute
  '/_authenticated/mis-pagos': typeof AuthenticatedMisPagosRoute
  '/_authenticated/mis-publicaciones': typeof AuthenticatedMisPublicacionesRoute
  '/_authenticated/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/publicar': typeof AuthenticatedPublicarRoute
  '/_authenticated/soporte': typeof AuthenticatedSoporteRoute
  '/auth/nueva-contrasena': typeof AuthNuevaContrasenaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/verificar-telefono': typeof AuthVerificarTelefonoRoute
  '/categoria/$id': typeof CategoriaIdRoute
  '/producto/$id': typeof ProductoIdRoute
  '/_authenticated/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/_authenticated/editar/$id': typeof AuthenticatedEditarIdRoute
  '/_authenticated/promocionar/$productoId': typeof AuthenticatedPromocionarProductoIdRoute
  '/_authenticated/reseña/$transaccionId': typeof AuthenticatedReseChar241aTransaccionIdRoute
  '/vendedor/$vendedorId/reseñas': typeof VendedorVendedorIdReseChar241asRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/politicas-seguridad'
    | '/privacidad'
    | '/terminos'
    | '/admin'
    | '/chats'
    | '/mis-destacados'
    | '/mis-pagos'
    | '/mis-publicaciones'
    | '/notificaciones'
    | '/perfil'
    | '/publicar'
    | '/soporte'
    | '/auth/nueva-contrasena'
    | '/auth/recuperar'
    | '/auth/verificar-telefono'
    | '/categoria/$id'
    | '/producto/$id'
    | '/chat/$chatId'
    | '/editar/$id'
    | '/promocionar/$productoId'
    | '/reseña/$transaccionId'
    | '/vendedor/$vendedorId/reseñas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/politicas-seguridad'
    | '/privacidad'
    | '/terminos'
    | '/admin'
    | '/chats'
    | '/mis-destacados'
    | '/mis-pagos'
    | '/mis-publicaciones'
    | '/notificaciones'
    | '/perfil'
    | '/publicar'
    | '/soporte'
    | '/auth/nueva-contrasena'
    | '/auth/recuperar'
    | '/auth/verificar-telefono'
    | '/categoria/$id'
    | '/producto/$id'
    | '/chat/$chatId'
    | '/editar/$id'
    | '/promocionar/$productoId'
    | '/reseña/$transaccionId'
    | '/vendedor/$vendedorId/reseñas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/politicas-seguridad'
    | '/privacidad'
    | '/terminos'
    | '/_authenticated/admin'
    | '/_authenticated/chats'
    | '/_authenticated/mis-destacados'
    | '/_authenticated/mis-pagos'
    | '/_authenticated/mis-publicaciones'
    | '/_authenticated/notificaciones'
    | '/_authenticated/perfil'
    | '/_authenticated/publicar'
    | '/_authenticated/soporte'
    | '/auth/nueva-contrasena'
    | '/auth/recuperar'
    | '/auth/verificar-telefono'
    | '/categoria/$id'
    | '/producto/$id'
    | '/_authenticated/chat/$chatId'
    | '/_authenticated/editar/$id'
    | '/_authenticated/promocionar/$productoId'
    | '/_authenticated/reseña/$transaccionId'
    | '/vendedor/$vendedorId/reseñas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PoliticasSeguridadRoute: typeof PoliticasSeguridadRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  CategoriaIdRoute: typeof CategoriaIdRoute
  ProductoIdRoute: typeof ProductoIdRoute
  VendedorVendedorIdReseChar241asRoute: typeof VendedorVendedorIdReseChar241asRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas-seguridad': {
      id: '/politicas-seguridad'
      path: '/politicas-seguridad'
      fullPath: '/politicas-seguridad'
      preLoaderRoute: typeof PoliticasSeguridadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$id': {
      id: '/categoria/$id'
      path: '/categoria/$id'
      fullPath: '/categoria/$id'
      preLoaderRoute: typeof CategoriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verificar-telefono': {
      id: '/auth/verificar-telefono'
      path: '/verificar-telefono'
      fullPath: '/auth/verificar-telefono'
      preLoaderRoute: typeof AuthVerificarTelefonoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/nueva-contrasena': {
      id: '/auth/nueva-contrasena'
      path: '/nueva-contrasena'
      fullPath: '/auth/nueva-contrasena'
      preLoaderRoute: typeof AuthNuevaContrasenaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/soporte': {
      id: '/_authenticated/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof AuthenticatedSoporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publicar': {
      id: '/_authenticated/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof AuthenticatedPublicarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificaciones': {
      id: '/_authenticated/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AuthenticatedNotificacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-publicaciones': {
      id: '/_authenticated/mis-publicaciones'
      path: '/mis-publicaciones'
      fullPath: '/mis-publicaciones'
      preLoaderRoute: typeof AuthenticatedMisPublicacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-pagos': {
      id: '/_authenticated/mis-pagos'
      path: '/mis-pagos'
      fullPath: '/mis-pagos'
      preLoaderRoute: typeof AuthenticatedMisPagosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-destacados': {
      id: '/_authenticated/mis-destacados'
      path: '/mis-destacados'
      fullPath: '/mis-destacados'
      preLoaderRoute: typeof AuthenticatedMisDestacadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/vendedor/$vendedorId/reseñas': {
      id: '/vendedor/$vendedorId/reseñas'
      path: '/vendedor/$vendedorId/reseñas'
      fullPath: '/vendedor/$vendedorId/reseñas'
      preLoaderRoute: typeof VendedorVendedorIdReseChar241asRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reseña/$transaccionId': {
      id: '/_authenticated/reseña/$transaccionId'
      path: '/reseña/$transaccionId'
      fullPath: '/reseña/$transaccionId'
      preLoaderRoute: typeof AuthenticatedReseChar241aTransaccionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promocionar/$productoId': {
      id: '/_authenticated/promocionar/$productoId'
      path: '/promocionar/$productoId'
      fullPath: '/promocionar/$productoId'
      preLoaderRoute: typeof AuthenticatedPromocionarProductoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editar/$id': {
      id: '/_authenticated/editar/$id'
      path: '/editar/$id'
      fullPath: '/editar/$id'
      preLoaderRoute: typeof AuthenticatedEditarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$chatId': {
      id: '/_authenticated/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedChatChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedMisDestacadosRoute: typeof AuthenticatedMisDestacadosRoute
  AuthenticatedMisPagosRoute: typeof AuthenticatedMisPagosRoute
  AuthenticatedMisPublicacionesRoute: typeof AuthenticatedMisPublicacionesRoute
  AuthenticatedNotificacionesRoute: typeof AuthenticatedNotificacionesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPublicarRoute: typeof AuthenticatedPublicarRoute
  AuthenticatedSoporteRoute: typeof AuthenticatedSoporteRoute
  AuthenticatedChatChatIdRoute: typeof AuthenticatedChatChatIdRoute
  AuthenticatedEditarIdRoute: typeof AuthenticatedEditarIdRoute
  AuthenticatedPromocionarProductoIdRoute: typeof AuthenticatedPromocionarProductoIdRoute
  AuthenticatedReseChar241aTransaccionIdRoute: typeof AuthenticatedReseChar241aTransaccionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedMisDestacadosRoute: AuthenticatedMisDestacadosRoute,
  AuthenticatedMisPagosRoute: AuthenticatedMisPagosRoute,
  AuthenticatedMisPublicacionesRoute: AuthenticatedMisPublicacionesRoute,
  AuthenticatedNotificacionesRoute: AuthenticatedNotificacionesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPublicarRoute: AuthenticatedPublicarRoute,
  AuthenticatedSoporteRoute: AuthenticatedSoporteRoute,
  AuthenticatedChatChatIdRoute: AuthenticatedChatChatIdRoute,
  AuthenticatedEditarIdRoute: AuthenticatedEditarIdRoute,
  AuthenticatedPromocionarProductoIdRoute:
    AuthenticatedPromocionarProductoIdRoute,
  AuthenticatedReseChar241aTransaccionIdRoute:
    AuthenticatedReseChar241aTransaccionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthNuevaContrasenaRoute: typeof AuthNuevaContrasenaRoute
  AuthRecuperarRoute: typeof AuthRecuperarRoute
  AuthVerificarTelefonoRoute: typeof AuthVerificarTelefonoRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNuevaContrasenaRoute: AuthNuevaContrasenaRoute,
  AuthRecuperarRoute: AuthRecuperarRoute,
  AuthVerificarTelefonoRoute: AuthVerificarTelefonoRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PoliticasSeguridadRoute: PoliticasSeguridadRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  CategoriaIdRoute: CategoriaIdRoute,
  ProductoIdRoute: ProductoIdRoute,
  VendedorVendedorIdReseChar241asRoute: VendedorVendedorIdReseChar241asRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
