// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client.ts";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    try {
      const { data } = await supabase.auth.getSession();
      const token = data.session?.access_token;
      if (typeof window !== "undefined") {
        try {
          localStorage.removeItem("supabase_down");
        } catch {
          // Ignore storage errors in restricted environments.
        }
      }
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
    } catch (err) {
      // If Supabase is unreachable (quota/credits/network), mark a client-side flag
      // and continue without Authorization header so the site stays accessible.
      if (typeof window !== "undefined") {
        try {
          localStorage.setItem("supabase_down", "1");
        } catch {
          // Ignore storage errors in restricted environments.
        }
      }
      return next({ headers: {} });
    }
  },
);
